Update DemoTables.hjson for elide 5.0.0.PR34
yavin-dev/demo-config pull request #1
Opened 2021-04-29 03:07 UTC by moizarafat

2021-04-29 14:14 UTC, jkusa approved these changes

2021-04-29 15:45 UTC, anupkumangodan approved these changes

2021-04-29 15:46 UTC, anupkumangodan requested changes
we need to bump up version in gradle build file

2021-04-29 15:47 UTC, anupkumangodan commented
@moizarafat https://github.com/yavin-dev/demo-config/blob/initial/build.gradle.kts#L8

2021-04-30 17:18 UTC, anupkumangodan approved these changes

2021-04-30 17:19 UTC, merged